// Kyanos Agent <-> Control Plane (Console) gRPC contract.
//
// Phase 7 (agent-grpc-control-plane). This file is the single source of truth
// shared by the Agent and the Console (Requirement 9.5): both sides compile
// against the generated bindings. The Console implementation is out of scope
// for Phase 7; this contract defines only the wire shape.
//
// Credential-safety invariant: NTRIP passwords must never leave the Agent in
// any event payload. AuthEvent therefore has NO password field by
// construction; there is intentionally no field in this contract that carries
// a credential value.
//
// Generate Go bindings with:
//   protoc --go_out=. --go_opt=module=kyanos \
//          --go-grpc_out=. --go-grpc_opt=module=kyanos \
//          proto/agent.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Connect_FullMethodName      = "/kyanos.agent.v1.AgentService/Connect"
	AgentService_ReportEvents_FullMethodName = "/kyanos.agent.v1.AgentService/ReportEvents"
	AgentService_ReportStatus_FullMethodName = "/kyanos.agent.v1.AgentService/ReportStatus"
	AgentService_StartCapture_FullMethodName = "/kyanos.agent.v1.AgentService/StartCapture"
	AgentService_StopCapture_FullMethodName  = "/kyanos.agent.v1.AgentService/StopCapture"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the control-plane API. The bidirectional control stream is
// realized as the Connect server stream (commands Console -> Agent) paired with
// the ReportEvents client stream (events Agent -> Console).
type AgentServiceClient interface {
	// Connect registers the Agent (AgentInfo) and returns the server stream of
	// control commands the Console sends to this Agent. (Req 2.1, 2.2, 2.3)
	Connect(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlCommand], error)
	// ReportEvents streams session diagnostic events from the Agent to the
	// Console. (Req 4.1)
	ReportEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SessionEvent, EventAck], error)
	// ReportStatus reports managed-pod set and health updates. (Req 2.4)
	ReportStatus(ctx context.Context, in *AgentStatus, opts ...grpc.CallOption) (*StatusAck, error)
	// StartCapture explicitly dispatches a capture task. (Req 3.1)
	StartCapture(ctx context.Context, in *CaptureTask, opts ...grpc.CallOption) (*TaskResponse, error)
	// StopCapture explicitly stops an in-progress capture task. (Req 3.6)
	StopCapture(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*TaskResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Connect(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentInfo, ControlCommand]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectClient = grpc.ServerStreamingClient[ControlCommand]

func (c *agentServiceClient) ReportEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SessionEvent, EventAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_ReportEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionEvent, EventAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportEventsClient = grpc.ClientStreamingClient[SessionEvent, EventAck]

func (c *agentServiceClient) ReportStatus(ctx context.Context, in *AgentStatus, opts ...grpc.CallOption) (*StatusAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusAck)
	err := c.cc.Invoke(ctx, AgentService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StartCapture(ctx context.Context, in *CaptureTask, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, AgentService_StartCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopCapture(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, AgentService_StopCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the control-plane API. The bidirectional control stream is
// realized as the Connect server stream (commands Console -> Agent) paired with
// the ReportEvents client stream (events Agent -> Console).
type AgentServiceServer interface {
	// Connect registers the Agent (AgentInfo) and returns the server stream of
	// control commands the Console sends to this Agent. (Req 2.1, 2.2, 2.3)
	Connect(*AgentInfo, grpc.ServerStreamingServer[ControlCommand]) error
	// ReportEvents streams session diagnostic events from the Agent to the
	// Console. (Req 4.1)
	ReportEvents(grpc.ClientStreamingServer[SessionEvent, EventAck]) error
	// ReportStatus reports managed-pod set and health updates. (Req 2.4)
	ReportStatus(context.Context, *AgentStatus) (*StatusAck, error)
	// StartCapture explicitly dispatches a capture task. (Req 3.1)
	StartCapture(context.Context, *CaptureTask) (*TaskResponse, error)
	// StopCapture explicitly stops an in-progress capture task. (Req 3.6)
	StopCapture(context.Context, *StopRequest) (*TaskResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Connect(*AgentInfo, grpc.ServerStreamingServer[ControlCommand]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentServiceServer) ReportEvents(grpc.ClientStreamingServer[SessionEvent, EventAck]) error {
	return status.Errorf(codes.Unimplemented, "method ReportEvents not implemented")
}
func (UnimplementedAgentServiceServer) ReportStatus(context.Context, *AgentStatus) (*StatusAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedAgentServiceServer) StartCapture(context.Context, *CaptureTask) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCapture not implemented")
}
func (UnimplementedAgentServiceServer) StopCapture(context.Context, *StopRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopCapture not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgentInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).Connect(m, &grpc.GenericServerStream[AgentInfo, ControlCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectServer = grpc.ServerStreamingServer[ControlCommand]

func _AgentService_ReportEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ReportEvents(&grpc.GenericServerStream[SessionEvent, EventAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportEventsServer = grpc.ClientStreamingServer[SessionEvent, EventAck]

func _AgentService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportStatus(ctx, req.(*AgentStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StartCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StartCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StartCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StartCapture(ctx, req.(*CaptureTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StopCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopCapture(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kyanos.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStatus",
			Handler:    _AgentService_ReportStatus_Handler,
		},
		{
			MethodName: "StartCapture",
			Handler:    _AgentService_StartCapture_Handler,
		},
		{
			MethodName: "StopCapture",
			Handler:    _AgentService_StopCapture_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentService_Connect_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReportEvents",
			Handler:       _AgentService_ReportEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
