// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadOpenssl111j returns the embedded CollectionSpec for Openssl111j.
func LoadOpenssl111j() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Openssl111jBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Openssl111j: %w", err)
	}

	return spec, err
}

// LoadOpenssl111jObjects loads Openssl111j and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*Openssl111jObjects
//	*Openssl111jPrograms
//	*Openssl111jMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadOpenssl111jObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadOpenssl111j()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// Openssl111jSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type Openssl111jSpecs struct {
	Openssl111jProgramSpecs
	Openssl111jMapSpecs
	Openssl111jVariableSpecs
}

// Openssl111jProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type Openssl111jProgramSpecs struct {
	SSL_readEntryNestedSyscall    *ebpf.ProgramSpec `ebpf:"SSL_read_entry_nested_syscall"`
	SSL_readEntryOffset           *ebpf.ProgramSpec `ebpf:"SSL_read_entry_offset"`
	SSL_readExEntryNestedSyscall  *ebpf.ProgramSpec `ebpf:"SSL_read_ex_entry_nested_syscall"`
	SSL_readExRetNestedSyscall    *ebpf.ProgramSpec `ebpf:"SSL_read_ex_ret_nested_syscall"`
	SSL_readRetNestedSyscall      *ebpf.ProgramSpec `ebpf:"SSL_read_ret_nested_syscall"`
	SSL_readRetOffset             *ebpf.ProgramSpec `ebpf:"SSL_read_ret_offset"`
	SSL_writeEntryNestedSyscall   *ebpf.ProgramSpec `ebpf:"SSL_write_entry_nested_syscall"`
	SSL_writeEntryOffset          *ebpf.ProgramSpec `ebpf:"SSL_write_entry_offset"`
	SSL_writeExEntryNestedSyscall *ebpf.ProgramSpec `ebpf:"SSL_write_ex_entry_nested_syscall"`
	SSL_writeExRetNestedSyscall   *ebpf.ProgramSpec `ebpf:"SSL_write_ex_ret_nested_syscall"`
	SSL_writeRetNestedSyscall     *ebpf.ProgramSpec `ebpf:"SSL_write_ret_nested_syscall"`
	SSL_writeRetOffset            *ebpf.ProgramSpec `ebpf:"SSL_write_ret_offset"`
}

// Openssl111jMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type Openssl111jMapSpecs struct {
	ActiveSslReadArgsMap  *ebpf.MapSpec `ebpf:"active_ssl_read_args_map"`
	ActiveSslWriteArgsMap *ebpf.MapSpec `ebpf:"active_ssl_write_args_map"`
	ConnEvtMap            *ebpf.MapSpec `ebpf:"conn_evt_map"`
	ConnEvtRb             *ebpf.MapSpec `ebpf:"conn_evt_rb"`
	ConnInfoMap           *ebpf.MapSpec `ebpf:"conn_info_map"`
	ControlValues         *ebpf.MapSpec `ebpf:"control_values"`
	FilterCgroupMap       *ebpf.MapSpec `ebpf:"filter_cgroup_map"`
	FilterMntnsMap        *ebpf.MapSpec `ebpf:"filter_mntns_map"`
	FilterNetnsMap        *ebpf.MapSpec `ebpf:"filter_netns_map"`
	FilterPidMap          *ebpf.MapSpec `ebpf:"filter_pid_map"`
	FilterPidnsMap        *ebpf.MapSpec `ebpf:"filter_pidns_map"`
	FirstPacketEvtMap     *ebpf.MapSpec `ebpf:"first_packet_evt_map"`
	FirstPacketRb         *ebpf.MapSpec `ebpf:"first_packet_rb"`
	Rb                    *ebpf.MapSpec `ebpf:"rb"`
	SslDataMap            *ebpf.MapSpec `ebpf:"ssl_data_map"`
	SslRb                 *ebpf.MapSpec `ebpf:"ssl_rb"`
	SslUserSpaceCallMap   *ebpf.MapSpec `ebpf:"ssl_user_space_call_map"`
	SyscallDataMap        *ebpf.MapSpec `ebpf:"syscall_data_map"`
	SyscallRb             *ebpf.MapSpec `ebpf:"syscall_rb"`
}

// Openssl111jVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type Openssl111jVariableSpecs struct {
	ConnEvtT_unused           *ebpf.VariableSpec `ebpf:"conn_evt_t_unused"`
	ConnIdS_tUnused           *ebpf.VariableSpec `ebpf:"conn_id_s_t_unused"`
	ConnInfoT_unused          *ebpf.VariableSpec `ebpf:"conn_info_t_unused"`
	ConnTypeT_unused          *ebpf.VariableSpec `ebpf:"conn_type_t_unused"`
	ControlValueIndexT_unused *ebpf.VariableSpec `ebpf:"control_value_index_t_unused"`
	EndpointRoleUnused        *ebpf.VariableSpec `ebpf:"endpoint_role_unused"`
	KInvalidFD                *ebpf.VariableSpec `ebpf:"kInvalidFD"`
	KernEvtDataUnused         *ebpf.VariableSpec `ebpf:"kern_evt_data_unused"`
	KernEvtSslDataUnused      *ebpf.VariableSpec `ebpf:"kern_evt_ssl_data_unused"`
	KernEvtUnused             *ebpf.VariableSpec `ebpf:"kern_evt_unused"`
	SockKeyUnused             *ebpf.VariableSpec `ebpf:"sock_key_unused"`
	StepT_unused              *ebpf.VariableSpec `ebpf:"step_t_unused"`
	TrafficDirectionT_unused  *ebpf.VariableSpec `ebpf:"traffic_direction_t_unused"`
	TrafficProtocolT_unused   *ebpf.VariableSpec `ebpf:"traffic_protocol_t_unused"`
}

// Openssl111jObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadOpenssl111jObjects or ebpf.CollectionSpec.LoadAndAssign.
type Openssl111jObjects struct {
	Openssl111jPrograms
	Openssl111jMaps
	Openssl111jVariables
}

func (o *Openssl111jObjects) Close() error {
	return _Openssl111jClose(
		&o.Openssl111jPrograms,
		&o.Openssl111jMaps,
	)
}

// Openssl111jMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadOpenssl111jObjects or ebpf.CollectionSpec.LoadAndAssign.
type Openssl111jMaps struct {
	ActiveSslReadArgsMap  *ebpf.Map `ebpf:"active_ssl_read_args_map"`
	ActiveSslWriteArgsMap *ebpf.Map `ebpf:"active_ssl_write_args_map"`
	ConnEvtMap            *ebpf.Map `ebpf:"conn_evt_map"`
	ConnEvtRb             *ebpf.Map `ebpf:"conn_evt_rb"`
	ConnInfoMap           *ebpf.Map `ebpf:"conn_info_map"`
	ControlValues         *ebpf.Map `ebpf:"control_values"`
	FilterCgroupMap       *ebpf.Map `ebpf:"filter_cgroup_map"`
	FilterMntnsMap        *ebpf.Map `ebpf:"filter_mntns_map"`
	FilterNetnsMap        *ebpf.Map `ebpf:"filter_netns_map"`
	FilterPidMap          *ebpf.Map `ebpf:"filter_pid_map"`
	FilterPidnsMap        *ebpf.Map `ebpf:"filter_pidns_map"`
	FirstPacketEvtMap     *ebpf.Map `ebpf:"first_packet_evt_map"`
	FirstPacketRb         *ebpf.Map `ebpf:"first_packet_rb"`
	Rb                    *ebpf.Map `ebpf:"rb"`
	SslDataMap            *ebpf.Map `ebpf:"ssl_data_map"`
	SslRb                 *ebpf.Map `ebpf:"ssl_rb"`
	SslUserSpaceCallMap   *ebpf.Map `ebpf:"ssl_user_space_call_map"`
	SyscallDataMap        *ebpf.Map `ebpf:"syscall_data_map"`
	SyscallRb             *ebpf.Map `ebpf:"syscall_rb"`
}

func (m *Openssl111jMaps) Close() error {
	return _Openssl111jClose(
		m.ActiveSslReadArgsMap,
		m.ActiveSslWriteArgsMap,
		m.ConnEvtMap,
		m.ConnEvtRb,
		m.ConnInfoMap,
		m.ControlValues,
		m.FilterCgroupMap,
		m.FilterMntnsMap,
		m.FilterNetnsMap,
		m.FilterPidMap,
		m.FilterPidnsMap,
		m.FirstPacketEvtMap,
		m.FirstPacketRb,
		m.Rb,
		m.SslDataMap,
		m.SslRb,
		m.SslUserSpaceCallMap,
		m.SyscallDataMap,
		m.SyscallRb,
	)
}

// Openssl111jVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadOpenssl111jObjects or ebpf.CollectionSpec.LoadAndAssign.
type Openssl111jVariables struct {
	ConnEvtT_unused           *ebpf.Variable `ebpf:"conn_evt_t_unused"`
	ConnIdS_tUnused           *ebpf.Variable `ebpf:"conn_id_s_t_unused"`
	ConnInfoT_unused          *ebpf.Variable `ebpf:"conn_info_t_unused"`
	ConnTypeT_unused          *ebpf.Variable `ebpf:"conn_type_t_unused"`
	ControlValueIndexT_unused *ebpf.Variable `ebpf:"control_value_index_t_unused"`
	EndpointRoleUnused        *ebpf.Variable `ebpf:"endpoint_role_unused"`
	KInvalidFD                *ebpf.Variable `ebpf:"kInvalidFD"`
	KernEvtDataUnused         *ebpf.Variable `ebpf:"kern_evt_data_unused"`
	KernEvtSslDataUnused      *ebpf.Variable `ebpf:"kern_evt_ssl_data_unused"`
	KernEvtUnused             *ebpf.Variable `ebpf:"kern_evt_unused"`
	SockKeyUnused             *ebpf.Variable `ebpf:"sock_key_unused"`
	StepT_unused              *ebpf.Variable `ebpf:"step_t_unused"`
	TrafficDirectionT_unused  *ebpf.Variable `ebpf:"traffic_direction_t_unused"`
	TrafficProtocolT_unused   *ebpf.Variable `ebpf:"traffic_protocol_t_unused"`
}

// Openssl111jPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadOpenssl111jObjects or ebpf.CollectionSpec.LoadAndAssign.
type Openssl111jPrograms struct {
	SSL_readEntryNestedSyscall    *ebpf.Program `ebpf:"SSL_read_entry_nested_syscall"`
	SSL_readEntryOffset           *ebpf.Program `ebpf:"SSL_read_entry_offset"`
	SSL_readExEntryNestedSyscall  *ebpf.Program `ebpf:"SSL_read_ex_entry_nested_syscall"`
	SSL_readExRetNestedSyscall    *ebpf.Program `ebpf:"SSL_read_ex_ret_nested_syscall"`
	SSL_readRetNestedSyscall      *ebpf.Program `ebpf:"SSL_read_ret_nested_syscall"`
	SSL_readRetOffset             *ebpf.Program `ebpf:"SSL_read_ret_offset"`
	SSL_writeEntryNestedSyscall   *ebpf.Program `ebpf:"SSL_write_entry_nested_syscall"`
	SSL_writeEntryOffset          *ebpf.Program `ebpf:"SSL_write_entry_offset"`
	SSL_writeExEntryNestedSyscall *ebpf.Program `ebpf:"SSL_write_ex_entry_nested_syscall"`
	SSL_writeExRetNestedSyscall   *ebpf.Program `ebpf:"SSL_write_ex_ret_nested_syscall"`
	SSL_writeRetNestedSyscall     *ebpf.Program `ebpf:"SSL_write_ret_nested_syscall"`
	SSL_writeRetOffset            *ebpf.Program `ebpf:"SSL_write_ret_offset"`
}

func (p *Openssl111jPrograms) Close() error {
	return _Openssl111jClose(
		p.SSL_readEntryNestedSyscall,
		p.SSL_readEntryOffset,
		p.SSL_readExEntryNestedSyscall,
		p.SSL_readExRetNestedSyscall,
		p.SSL_readRetNestedSyscall,
		p.SSL_readRetOffset,
		p.SSL_writeEntryNestedSyscall,
		p.SSL_writeEntryOffset,
		p.SSL_writeExEntryNestedSyscall,
		p.SSL_writeExRetNestedSyscall,
		p.SSL_writeRetNestedSyscall,
		p.SSL_writeRetOffset,
	)
}

func _Openssl111jClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed openssl111j_arm64_bpfel.o
var _Openssl111jBytes []byte
